### PR TITLE
Update i18n_data to 0.13.0 and drop support for rubies <2.5

### PR DESCRIPTION
**Pull request by pmor**

### CODE REVIEW

**Comment by pmor** [comment]
Build fails because i18n_data 0.13.0 only supports Ruby 2.5 and later. 
We have an open PR (#644) that drops support for 2.3 and earlier, but still leaves support for 2.4.

@rposborne Should we consider dropping support for 2.4 as well?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by rposborne** [comment]
@pmor this is great. 

I have merged the majority of the PR's that you approved and intend to cut a release of that prior to going after any of these breaking changes. 

Lets drop the rubies we need to, 2.4 if we have to and get this in.

**Comment by basex** [comment]
Can this be merged now?

**Review by williamweckl — APPROVED** [review]

**Comment by basex** [comment]
@rposborne @pmor ping

**Review by rposborne — APPROVED** [review]

**Comment by rposborne** [comment]
Prepping this for a 4.0 release.

**Pull request merged**
