### PR TITLE
Fixes #633 and updates geocoder searches

### LINKED ISSUE #633: `update_cldr_subdivison_data` Rake task broken due to CLDR repo change
As of CLDR-36 release (http://cldr.unicode.org/index/downloads/cldr-36) the repo moved to GitHub (https://github.com/unicode-org/cldr), and this breaks the `update_cldr_subdivison_data` Rake task

### PR DESCRIPTION
**Pull request by mezza**
Explicitly set the geocoder to use :google, which does require an API key, and updated the countries and subdivisions. Using the :region param and modifying the search terms addresses ambiguous searches

Could you please merge and cut a new gem?

### CODE REVIEW

**Comment by mezza** [comment]
Retracting pull request after seeing CI failures

**Comment by mezza** [comment]
Specs now passing

**Comment by mezza** [comment]
@pmor Is a new gem going to be cut soon?

**Comment by pmor** [comment]
@mezza I have no idea. At this point it's up to @rposborne and @hexorx.

**Comment by pmor** [comment]
@rposborne

**Comment by rposborne** [comment]
Lets resolve conflicts on this and get this merged.   Sorry folks, have a newborn!

**Comment by pmor** [comment]
@rposborne Congratulations then! Happy holidays! 🎄

**Comment by rposborne** [comment]
@pmor let us get this in, you should now have merge rights. @mezza I'll cut a 4.0 release when this is merged.  I am able now to delegate some of these tasks so things should move a bit easier.

**Comment by rposborne** [comment]
@mezza could you resolve conflicts?

**Comment by mezza** [comment]
@rposborne Not sure why 2.6.6 test is failing but otherwise conflicts resolved.

**Comment by olleolleolle** [comment]
`thread_safety_spec` 

I went in there to reproduce the problem. When I set `nthreads = 3` I was able to get the same issue that the 2.6.6 CI matrix element had in this test run.

What if the 100 threads in the test were ordered just-so, in that run, so they didn't turn it into something bad?

**Comment by rposborne** [comment]
We certainly have some flaky / order-dependent tests in the mix. Points to whoever fixes those!

**Pull request merged**
