### PR TITLE
Update GT subdivisions

### PR DESCRIPTION
**Pull request by sineed**
https://www.iso.org/obp/ui/#iso:code:3166:GT

> 2021-11-25 | Change of subdivision code from GT-AV to GT-16, GT-BV to GT-15, GT-CM to GT-04, GT-CQ to GT-20, GT-ES to GT-05, GT-GU to GT-01, GT-HU to GT-13, GT-IZ to GT-18, GT-JA to GT-21, GT-JU to GT-22, GT-PE to GT-17, GT-PR to GT-02, GT-QC to GT-14, GT-QZ to GT-09, GT-RE to GT-11, GT-SA to GT-03, GT-SM to GT-12, GT-SO to GT-07, GT-SR to GT-06, GT-SU to GT-10, GT-TO to GT-08, GT-ZA to GT-19; Update Code Source

### CODE REVIEW

**Comment by pmor** [comment]
Thanks for the PR!

**Comment by sineed** [comment]
When do you plan to make a new release?

**Comment by pmor** [comment]
@sineed New release will be pushed today

**Comment by sineed** [comment]
Thanks!

**Pull request merged**
