### PR TITLE
Missing alternative names for GB and US

### PR DESCRIPTION
**Pull request by dima4p**

### CODE REVIEW

**Comment by pmor** [comment]
Thanks for the PR!

Could you please remove the changes to `Rakefile` and `lib/countries/cache/countries.json`? 
We regenerate the cache before a new release, otherwise it's a constant source of merge conflicts, and the Rakefile change appears to be unrelated to this PR.

**Comment by dima4p** [comment]
> Could you please remove the changes to `Rakefile` and `lib/countries/cache/countries.json`? We regenerate the cache before a new release, otherwise it's a constant source of merge conflicts, and the Rakefile change appears to be unrelated to this PR.

With `lib/countries/cache/countries.json` it is clear, but what is wrong with  `Rakefile`? The change is to keep the order of the keys in `lib/countries/cache/countries.json`.

**Comment by pmor** [comment]
Ok, the Rakefile change makes sense, but please see https://github.com/countries/countries#please-do-not-submit-pull-requests-on-cache regarding `lib/countries/cache/countries.json`

**Comment by dima4p** [comment]
Additionally, reverting `lib/countries/cache/countries.json` breaks the specs…

**Pull request merged**
