### PR TITLE
Suggestion for link to the gem that makes integration with 'countries'

### PR DESCRIPTION
**Pull request by pedrofurtado**
@rposborne :+1: 

The integration will be increased in features, with more facilities to use inside Rails application.

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@rposborne Let me know your suggestions :+1: :handshake:

**Comment by pedrofurtado** [comment]
@rposborne

**Comment by pedrofurtado** [comment]
@rposborne 👍

**Comment by pedrofurtado** [comment]
@rposborne :+1:

**Comment by pedrofurtado** [comment]
@rposborne

**Comment by pedrofurtado** [comment]
@rposborne

**Comment by pmor** [comment]
That gem seems to be abandoned, so I'm closing this PR

**Pull request closed without merging**
