### PR TITLE
Update KG.yaml

### PR DESCRIPTION
**Pull request by newstler**
Add Kyrgyz

### CODE REVIEW

**Comment by rposborne** [comment]
@newstler Is `Kyrgyz` an unofficial or a slang name?  Kyrgyz seems to be the official name for the country?  Is this data incorrect in our translations?

**Comment by newstler** [comment]
Well, I'm not sure, but one of the APIs I use (British one) returns "Kyrgyz" instead of "Kyrgyzstan" so  `ISO3166::Country.find_country_by_name("Kyrgyz")` returns `nil`. So I thought this update may resolve this.

**Comment by newstler** [comment]
Actually I just found that this code doesn't work anyway. How do I associate `Kyrgyz` with `KG` so `ISO3166::Country.find_country_by_name("Kyrgyz")` would return it?

**Comment by pmor** [comment]
@rposborne
The official name is "The Kyrgyz Republic", while "Kyrgystan" is the ISO "short name".(https://www.iso.org/obp/ui/#iso:code:3166:KG)

I have no idea if "Kyrgyz" alone is a commonly used unofficial name, which is what's been added in this PR, so not sure if I should accept or close.

**Pull request closed without merging**
