### PR TITLE
Fix ISO3166::Data.register loading of nested hashes, eg: geo data.

### PR DESCRIPTION
**Pull request by pmor**
This addresses the issue mentioned in https://github.com/countries/countries/pull/397#issuecomment-846543094

(cc @kg-currenxie)

### CODE REVIEW

**Comment by Frexuz** [comment]
@pmor any gem release soon? :) thanks

**Comment by pmor** [comment]
@Frexuz Not sure, it's @rposborne that has been deciding on when the releases happen.

**Comment by rposborne** [comment]
@pmor you are free to do releases. Ship it :)

**Comment by Frexuz** [comment]
Confirmed fixed 👍

**Pull request merged**
